CREATE TABLE IF NOT EXISTS teste (
  id BIGINT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(45) NOT NULL,
  descricao VARCHAR(255) NOT NULL,
  tipo VARCHAR(45) NULL,
  ativo BIT(1) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX nome_UNIQUE (nome ASC))
ENGINE = InnoDB;